--- # Installing Docker and its requirements
- hosts: server
  remote_user: root
  tasks:
  - name: Remove a directory to store the fedmonitor image source files
    file:
      path: /root/federated_learning/server
      state: absent
  - name: Create a directory to store the fedserver image source files
    file:
      path: /root/federated_learning
      state: directory
  - name: Remove image
    docker_image:
      name: fedserver
      state: absent
      force_absent: yes
    vars:
      ansible_python_interpreter: /bin/python3
  - name: remove container
    docker_container:
      name: fedserver
      state: absent
      force_kill: yes
    vars:
      ansible_python_interpreter: /bin/python3      
  - name: Pull the fedserver image source files from my local machine
    copy:
      src: /home/mashrafhemdan/fl_deployment/federated_learning_infrastructure/fed/server
      dest: /root/federated_learning
  - name: Pull the utils source file from my local machine
    copy:
      src: /home/mashrafhemdan/fl_deployment/federated_learning_infrastructure/fed/monitor/utils.py
      dest: /root/federated_learning/server
  - name: Build server and with build args
    docker_image:
      name: fedserver
      build:
        path: /root/federated_learning/server
        # args:
        #   listen_port: 8080
      source: build
    vars:
      ansible_python_interpreter: /bin/python3
  - name: Run fedserver container from the image file
    docker_container:
      name: fedserver
      state: started
      image: fedserver
      detach: no
      # interactive: yes
      # tty: yes
      recreate: yes
      cleanup: yes
      ports:
        - "8080:8080"
      volumes:
        - /root/data:/data
      restart_policy: always
    register: server_output
    vars:
      ansible_python_interpreter: /bin/python3

  - name: Server Output
    debug:
      msg: "Docker said: {{ server_output }}"
